import { Collection, Product, Room } from "@/types";

export const syncStatus = {
  source: "1C:Управление торговлей",
  lastSync: "26 апреля 2026, 19:42",
  interval: "каждые 15 минут",
  productsUpdated: 1240,
  priceAccuracy: 98,
  stockAccuracy: 96,
};

export const roomLabels: Record<Room, string> = {
  "living room": "Гостиная",
  bedroom: "Спальня",
  kitchen: "Кухня",
  hallway: "Прихожая",
  bathroom: "Ванная",
};

export const mountingLabels = {
  ceiling: "Потолочный монтаж",
  wall: "Настенный монтаж",
  track: "Трековая система",
  recessed: "Встраиваемый",
  pendant: "Подвесной",
} as const;

export const styleLabels = {
  modern: "Современный",
  classic: "Классика",
  loft: "Лофт",
  minimalism: "Минимализм",
  "art deco": "Art Deco",
} as const;

export const demoProducts: Product[] = [
  {
    id: "lum-101",
    name: "Orlo Brass Chandelier",
    article: "LUM-101",
    brand: "Flos",
    price: 1240000,
    discountPrice: 1120000,
    category: "Люстры",
    style: "modern",
    room: ["living room", "bedroom"],
    color: "Warm brass",
    lightColor: "4000K",
    power: 60,
    mounting: "ceiling",
    images: ["/lumain/haydi-pendant.jpg"],
    stock: 15,
    updatedAt: "2026-04-26T19:42:00.000Z",
    luminousFlux: 5200,
    recommendedArea: "18-24 м²",
    dimensions: { length: 720, width: 720, height: 420 },
    lampBase: "E14",
    bulbsIncluded: false,
    supportedBulbs: ["LED E14", "диммируемые LED", "теплый и нейтральный свет"],
    material: "Латунь, стекло, хрусталь",
    protection: "IP20",
    warranty: "24 месяца",
    description: "Декоративная люстра с теплым латунным акцентом для парадных зон, гостиной и мастер-спальни.",
    finish: "Латунь / прозрачное стекло",
    voltage: "220-240 V",
    cri: "90 CRI",
    installationType: "Монтаж на планку",
    application: ["Гостиная", "Зал", "Мастер-спальня", "Двусветное пространство"],
  },
  {
    id: "lum-202",
    name: "Vela Wall Sconce",
    article: "LUM-202",
    brand: "Artemide",
    price: 286000,
    category: "Бра",
    style: "classic",
    room: ["hallway", "bedroom"],
    color: "Brushed brass",
    lightColor: "2700K",
    power: 15,
    mounting: "wall",
    images: ["/lumain/haydi-sconce.jpg"],
    stock: 24,
    updatedAt: "2026-04-26T19:40:00.000Z",
    luminousFlux: 1200,
    recommendedArea: "4-8 м²",
    dimensions: { length: 180, width: 140, height: 320 },
    lampBase: "G9",
    bulbsIncluded: true,
    supportedBulbs: ["LED G9", "теплый свет", "лампы до 15 Вт"],
    material: "Латунь, матовое стекло",
    protection: "IP20",
    warranty: "18 месяцев",
    description: "Компактное бра для сценариев мягкой подсветки, прикроватной группы и коридорных акцентов.",
    finish: "Шлифованная латунь / матовое стекло",
    voltage: "220-240 V",
    cri: "90 CRI",
    installationType: "Настенное подключение",
    application: ["Спальня", "Детская", "Коридор", "Прикроватная зона"],
  },
  {
    id: "lum-303",
    name: "Linea Magnetic Track",
    article: "LUM-303",
    brand: "Maytoni",
    price: 174000,
    category: "Трековые",
    style: "loft",
    room: ["kitchen", "hallway"],
    color: "Matte black",
    lightColor: "4000K",
    power: 40,
    mounting: "track",
    images: ["/lumain/haydi-track.jpg"],
    stock: 40,
    updatedAt: "2026-04-26T19:39:00.000Z",
    luminousFlux: 3600,
    recommendedArea: "10-16 м²",
    dimensions: { length: 980, width: 120, height: 1100 },
    lampBase: "GU10",
    bulbsIncluded: false,
    supportedBulbs: ["LED GU10", "направленный свет", "заменяемые лампы"],
    material: "Порошковая сталь, алюминий",
    protection: "IP20",
    warranty: "24 месяца",
    description: "Линейный трековый светильник для кухни, коридора и коммерческих зон, где важен точный направленный свет.",
    finish: "Черный матовый",
    voltage: "48 V",
    cri: "90 CRI",
    installationType: "Магнитный шинопровод",
    application: ["Кухня", "Коридор", "Гардероб", "Коммерческий интерьер"],
  },
  {
    id: "lum-404",
    name: "Aurea Pendant 600",
    article: "LUM-404",
    brand: "Masiero",
    price: 696000,
    category: "Подвесы",
    style: "minimalism",
    room: ["living room", "kitchen"],
    color: "Soft gold",
    lightColor: "4000K",
    power: 42,
    mounting: "pendant",
    images: ["/lumain/haydi-hero-chandelier.jpg"],
    stock: 12,
    updatedAt: "2026-04-26T19:38:00.000Z",
    luminousFlux: 4100,
    recommendedArea: "12-18 м²",
    dimensions: { length: 600, width: 600, height: 900 },
    lampBase: "Встроенный LED",
    bulbsIncluded: true,
    supportedBulbs: ["LED модуль", "теплый свет", "ресурс 30 000 часов"],
    material: "Алюминий, опаловое стекло",
    protection: "IP20",
    warranty: "36 месяцев",
    description: "Подвес для острова, столовой группы или центральной зоны, когда нужен чистый силуэт и мягкий рассеянный свет.",
    finish: "Мягкое золото / опаловое стекло",
    voltage: "220-240 V",
    cri: "90 CRI",
    installationType: "Подвес на тросах",
    application: ["Столовая", "Зал", "Кухонный остров", "Переговорная"],
  },
];

export function getProductById(id: string) {
  return demoProducts.find((product) => product.id === id);
}

export function getRelatedProducts(currentId: string, limit = 3) {
  return demoProducts.filter((product) => product.id !== currentId).slice(0, limit);
}

export const demoCollections: Collection[] = [
  {
    id: "1",
    name: "Квартира на Ленина",
    designerId: "anna",
    items: ["lum-101", "lum-202", "lum-404"],
    shareToken: "kvartira-lenina",
  },
  {
    id: "2",
    name: "Офис IT-компании",
    designerId: "anna",
    items: ["lum-303", "lum-404"],
    shareToken: "office-it",
  },
  {
    id: "3",
    name: "Загородный дом",
    designerId: "anna",
    items: ["lum-101", "lum-202", "lum-303"],
    shareToken: "country-house",
  },
];
